### ISSUE TITLE
macOS Catalina Support please

### ISSUE THREAD

**Issue by algorithmor** [tableau/Logshark#124]
Can we please have support for >= 10.15, i.e. Catalina, Big Sur support on this. Its been over an year now.

**Comment by Xantrul** [comment]
Hi,
This is on our backlog, but currently we don't have any firm plans on when we get to it and, frankly speaking, it is not high on the priority list because internally we have very few users running LogShark on macOS and we don't have any information on what is the demand for LogShark on macOS externally.

I have 2 asks for the community to help us prioritize this feature appropriately:
1. `+1` original message if you're also interested in running LogShark on macOS Catalina or newer
2. Notarization of LogShark might be a tricky process, as we have binary dependencies bundled in the package. One workaround we are going to look into is to run LogShark in a Docker container. Let us know in the comments if running LogShark through Docker would be an acceptable solution for you.

**Comment by jastix** [comment]
Would be great to have LogShark available in a Docker container.
We encountered this issue that some team members cannot run LogShark because they upgraded to MacOS 10.15.

**Comment by aishydevil12286** [comment]
Possibility to run in docker would be awesome. That would definitely solve the issue for all platforms.

**Comment by Xantrul** [comment]
We've released LogShark v4.2.1 today and included instructions on how to run LogShark in Docker.

I tested this with macOS Catalina and it works just fine. I don't have access to Big Sur yet and can't test there, but if Big Sur is running on Intel CPU and can run Docker - I assume it should work exactly the same. M1 is a big question mark at this point though - it looks like dotnet SDK is not even done for this platform yet (https://github.com/dotnet/runtime/issues/43313)

I gonna close this issue for now as Docker instructions should be enough to allow to run LogShark on macOS 10.15+ in most cases. If anyone has any follow up questions or requests - please feel free to reopen this issue or open a new one.
