### ISSUE TITLE
Logshark connects to more-local Windows machines, but not Cloud sourced Linux servers

### ISSUE THREAD

**Issue by bingchenzo** [tableau/Logshark#125]
I realize this is a long shot, and I'm not able to provide a ton of details, but has anyone overcome an issue wherein Logshark can't publish to Tableau Servers on Linux in a cloud?

The error I am getting is :
fail: LogShark.Writers.WorkbookPublisher[0]
      Exception encountered when attempting to sign in or create the project: Http error returned while sending a request. Error reported: Call failed with status code 401 (Unauthorized): POST https://adsd-web009-test.compute.rest.of.fqdn/api/2.8/auth/signin. Response body {"error":{"summary":"Signin Error","detail":"Error signing in to Tableau Server","code":"401001"}}
fail: LogShark.LogSharkRunner[0]
      Workbook publisher failed to connect to the Tableau Server or create project for the results. Exception message: Http error returned while sending a request. Error reported: Call failed with status code 401 (Unauthorized): POST https://adsd-web009-test.compute.rest.of.fqdn/api/2.8/auth/signin. Response body {"error":{"summary":"Signin Error","detail":"Error signing in to Tableau Server","code":"401001"}}
info: LogShark.Program[0]

**Comment by Xantrul** [comment]
Hi,
LogShark uses Tableau Server REST API to talk to Tableau Server, so it shouldn't matter where the server is hosted or what platform it is running on.

According to [docs,](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref.htm#sign_in) error code 401001 means:
> The credentials (name or password, or personal access token name or secret) are invalid for the specified site, or the site content URL is invalid.

More often than not the problem is the content URL, as `content URL` != `Site name`. See [this Issue](https://github.com/tableau/Logshark/issues/102) for guidance on how to find content URL.

**Comment by bingchenzo** [comment]
Thanks!

same configuration works for the original system on Windows, locally. the
target system with error was exported from the local windows version.

is it possibly a password issue between windows and linux?

**Comment by Xantrul** [comment]
Please try the following simple test:
1. Open the URL in question in web browser
2. Login using the credentials LogShark has in config (this confirms that credentials work as expected)
3. Once logged in - note the site id included in the url and make sure it matches what LogShark has (depending on how site/sever was exported and imported into the target system, content URL might've changed).

If credentials work and site's content URL on the target system matches what LS has in its config, this is getting tricky... As a next step I would recommend to use Postman (or your favorite HTTP client) to attempt to create a sign in REST API request to the target Tableau Server manually and see if it works. Use doc link I mentioned before as a reference. LogShark simply calls that API, so we need to know whatever the problem is with LogShark or with REST API itself

**Comment by bingchenzo** [comment]
The URLs for the source site that was exported, and the target site that isn't working, are the same, aside from the domain.

When I switch which one I publish to, I am only changing the URL parameter for the Server info in the config file.


Could a SAML layer be causing the issue?

**Comment by Xantrul** [comment]
> The URLs for the source site that was exported, and the target site that isn't working, are the same, aside from the domain.
> When I switch which one I publish to, I am only changing the URL parameter for the Server info in the config file.

Did you have a chance to check content URL on the new site though? If you exported site from one server and imported it into another, content URL might have changed (it is generated automatically). Simply login into the new site and note the site part in the url (i.e. in https://awesome-server.tableau.com/#/site/thisisyoursitename/home content URL value is `thisisyoursitename`)

> Could a SAML layer be causing the issue?

It is possible. From what I see in the docs, you might have to create a Tableau Server local user for use with REST API. See the note at the end of [this section](https://help.tableau.com/current/server/en-us/saml_requ.htm#user-management-requirements).
