### ISSUE TITLE
Logshark - Not creating the workbook

### ISSUE THREAD

**Issue by BalaKumaara** [tableau/Logshark#42]
I setup the logshark and PostgreSQL as said and when i try to run the command, i see the database in the Postgre but no tables in it and the folder(Empty) in Output\ is getting created  but the workbooks are not getting created in the Output folder.

Please help, Below is the command i run and i am running in my local machine against the downloaded log files.

1.) logshark Target\logs.zip --plugins VizqlDesktop --startlocalmongo
2.) logshark Target\logs.zip --plugins VizqlDesktop 

Also i am trying to run only the VizqlDesktop plug in as my scope of work is around that and the size of the log files is pretty huge as well.

Any help is greatly appreciated.

Thanks,
Bala

**Comment by Sandeepr21891** [comment]
Hey Bala, Even I am facing the same problem unable to find workbooks generated by Logshark. Did you figured out solution ? if so can you please share.

**Comment by rahulmotwani** [comment]
Hi @BalaKumaara,

Sorry to hear that you are experiencing issues with Logshark. 

1. Can you share your Logshark config file as well as the logs from the Logshark run? This will help diagnose the issue. 
2. Can you confirm that you have setup Postgres and Logshark as per the instructions outlined at [Configure Logshark](https://tableau.github.io/Logshark/docs/logshark_install#configure-logshark).
2. As noted in the documentation, the built-in MongoDB is really only sufficient for logsets 2GB or smaller. Any larger than that and MongoDB on Windows tends to become a bottleneck. If you are going to be regularly processing larger logsets, then you should see a huge boost from setting up an external MongoDB server, preferably on a Linux host in order to benefit from more performant memory mapping.

**Comment by Sandeepr21891** [comment]
Hi Rahul, thank you very much for your response. I could able to rectify my
mistake in config file and solved the problem.

Thank you
sandeep

**Comment by rahulmotwani** [comment]
Great to hear @Sandeepr21891 . I'm going to wait for @BalaKumaara to respond, before I close this issue out.

**Comment by Sandeepr21891** [comment]
Sure Rahul, can you please upload a video installing and working using
Logshark. I hope it will be very helpful for future users :)
I have came across many working using splunk but logshark is working really
good.

Thank you
Sandeep

**Comment by BalaKumaara** [comment]
Hi Rahul,
I did a complete reinstallation and changed the config file as suggested and it did resolved the issue.
Thanks,
Bala

**Comment by rahulmotwani** [comment]
Awesome. Glad to hear that @BalaKumaara!
