### ISSUE TITLE
How to analysis tdeserver log?

### ISSUE THREAD

**Issue by YapingWu** [tableau/Logshark#48]
Hi,
I noticed that after analysis，there is not a result is related to tdeserver.
How can I analysis tdeserver log?

**Comment by eliong** [comment]
Are you using version 2.1? Wasn't the TDE analysis retired in the patch notes for version 2.1? You may want to use 2.0 if you're still using a non-Hyper Tableau Version.
Copied from the notes on 2.1
"Logshark 2.1 includes numerous fixes and improvements made since the previous release, but the most notable changes are:

Support for log sets generated by new versions of Tableau Server (including Tableau Server on Linux)
New plugin: Hyper
**Retired plugin: DataEngine**"

**Comment by YapingWu** [comment]
I am using version 2.0.Here's the result:
![image](https://user-images.githubusercontent.com/16968238/41696733-31f58826-7548-11e8-8aa1-5c36b32ab30f.png)

**Comment by Xantrul** [comment]
Hi,
In version 2.0 DataEngine plugin is present, but disabled by default (due to poor performance). If you would like to run it on your log set, you'll have to either add it to the list in LogShark.config, or specify this plugin with "--plugin" parameter in command prompt
