### ISSUE TITLE
Feature Request: Save output in PostgreSQL

### ISSUE THREAD

**Issue by jagannath-patro** [tableau/Logshark#67]
Logshark v2.1 and below had the ability to save output in PostgreSQL database. This provided the ability to have the Tableau reports connected to the PostgreSQL database. With that, it was easier to have a single pane view of data for a range of dates in a single report.
Now with Logshark v3.0 and v3.0.1, the outputs are stored in hyper extracts instead of PostgreSQL. With this, don't know if there's an option to see all the data for a given data range in a single report.

**Comment by Xantrul** [comment]
Hi jagannath-patro,
Just to make sure - is the main point of the request to have ability to append data to the existing results? I.e. if we added an option to append output of runB to the existing hyper extracts and workbooks generated by runA, would this address your use case?

**Comment by jagannath-patro** [comment]
Hi Xantrul,
Yes, the main point would be to append the data to the existing results. And if that option is added it would really help.
But the storing of data in PostgreSQL has more advantages:

1. Workbook doesn't needs to be published again and again.
2. Data was centralized in a PostgreSQL database which allows to build other workbooks/Viz on top of it.
3. As the data was centralized in the database, the backup part was much easier.

Although this has a negative effect on the performance.

Any chance of having both the options, store data in database or/and in extracts?

**Comment by hanshu51** [comment]
Hi,

The command-line option '--dbname <databasename>' still can be specified. But it is not working.
When i specify this, no database in the PostgreSQL is created and so nothing is saved of previous runs.
This option worked pre version 3.0 as stated in the OP.

The logshark run reports:
     Plugin backing data was written to Postgres database 'localhost:5432\wkptest_1'.
But the database 'wkptest_1' is not created.

I agree with Jagannath-patro that storing results into PostgreSQL has more advantages.

**Comment by bermetj** [comment]
Hi @jagannath-patro,
As much as we would love to address every user's request, Logshark's new features are driven by our internal needs and then shared with the community. Currently, we don't anticipate an internal need to save the output as PostgreSQL database. However, we welcome you to add your own plugins and share your work.

**Comment by bermetj** [comment]
Hi @hanshu51,
My apologies, that command reference should have been removed from the instructions as it refers to a functionality that is no longer available in this version.

**Comment by jagannath-patro** [comment]
Hi @bermetj,
Thanks for the reply. I can understand that.

but as suggested by @Xantrul,  could we append the output of a "run" be appended to an existing extract? that would really help.

**Comment by timothyvermeiren** [comment]
I'm a bit surprised to see this functionality gone, too. I understand that you're driven by internal needs, but how do you gather data from the logs over an extended period of time? We were running this nightly against the logs of the previous day, and appending the data in the PostgreSQL database. This was the perfect repository for gathering this data historically, and adding to it day by day.

So one of two things: either there is another way to store this data historically (unioning hyper files is not possible), or we may have been "misusing" the tool where it was designed to view only a snapshot (but the workbooks seem to indicate otherwise).

Everyone's thoughts on this are welcome!

**Comment by jagannath-patro** [comment]
Hi @timothyvermeiren, we did the same as well. We used to run it nightly and had all the logs centralized in the database, making it easy to see the trends historically.
Hopefully, the functionality of storing the log in the database is back.

**Comment by javanic** [comment]
Hi folks, first let me say sorry for taking away a capability that some of you were using to provide historical trending. That capability really was not designed as a Logshark feature per se,--it was capability provided by database persistence. Over the years of Logshark support we frequently were asked to simplify the cost of setup and maintenance of Logshark. The standalone Postgres database was the target of those requests for simplification. Internally, the Postgres database was a bottleneck for our own Logshark usage. We run hundreds of logsets through Logshark every day using multiple Logshark runners in parallel. We could not scale up our runner capacity because we were throttled by the database's ability to keep up. 

Enter Hyper extracts. We simplified Logshark's setup, increased its throughput capacity, and provided end users with faster viz load times and made sharing easier. But I must admit that we did not understand how _everyone_ was using Logshark. 

We have put the request to append new run data to an existing hyper extract onto our road map, though it has some challenges and limitations of its own. However, before we develop appending capability we will be rewriting Logshark to make it between 4 to 6 times faster than it is today. We have our prototype completed and it is looking promising. We believe that simplicity of setup, speed of processing logs, speed of viewing results, and ease of sharing are priority requirements for our internal and customer users. If we have resolved the challenges with appending to hyper extracts, we will include that ability with the new, faster Logshark.

**Comment by dwalker3rd** [comment]
i have no qualms with you telling us NO.  nor do i believe it necessary that you explain yourself.   but I  much appreciate that you did.  easier to accept when we can understand why AND when we can see where you're going.  with that Timothy and I perhaps still disagree [with you] but we can commit to your decision.  we'll be looking for that 4-6x faster version!  and in the meantime, we can append the extracts ourselves in script.

the one thing that still bugs me:  "Logshark's new features are driven by our internal needs and then shared with the community."  OK, i get that Tableau built this for themselves.  And when they did share it, they open sourced it so we could fork it and mod as we needed (if someone has the time, you could enhance this!  think .net log wrappers).  Guess i've never seen a difference between Tableau and the community and there's the rub.  You built something you needed - turned out we needed it - voila, we're all using it together.  should be a particpatory community - not an us and them.

thanks for taking the time to give a better, more indepth answer.

**Comment by Xantrul** [comment]
LogShark v4.1 was [released](https://github.com/tableau/Logshark/releases/tag/v4.1) today and it has both features mentioned in this issue:

- Users can can now choose between Hyper and PostgreSQL output
- LogShark can append results of the current run to the results of the previous (runs) for both Hyper and PostgreSQL

[Documentation link](https://tableau.github.io/Logshark/docs/logshark_postgres)

Plz note that to append PostgreSQL results, you don't need to use `--append-to` parameter: if LogShark sees that database with the given name already exists, it will add any missing tables and pushes results into the existing database.
Exclusively for PostgreSQL writer, we also added a new table `logshark_runs` which contains high-level metadata from each run and all records in all other tables have a reference to the run ID they are from.
