### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by yapnel** [tableau/Logshark#74]
Environment: Tableau 2018.3 3-node cluster

Installed the latest version of logshark on a windows server 2012 R2 with admin privileges. Took a snapshot of the Tableau logs.

Executed the below command got a print on the console "Logshark user configuration.." and immediately it finishes. Filled in the correct configurations too.
logshark log.zip -s -p

Checked the log file and it doesn't have any error messages apart from these. What could be happening? Please advise. Thanks

2019-01-23 22:45:13,388 (null) (null) [1] DEBUG Logshark.CLI.Program - Logshark execution arguments: C:\Temp\logs.zip -s -p
2019-01-23 22:45:13,481 (null) (null) [1] INFO Logshark.RequestModel.Config.LogsharkConfigReader - Loading Logshark user configuration..
2019-01-23 22:45:13,513 (null) (null) [1] DEBUG Logshark.RequestModel.Config.LogsharkConfigReader - Loaded user configuration!

**Comment by Xantrul** [comment]
Hi yapnel,

I looked at the logs from successful run of Logshark and looks like the next message is expected to be about cleaning data from local Mongo DB. Since you never get there, most likely there is a problem with starting local copy of Mongo: i.e. current account doesn't have privileges to start Mongo, or its default port - 27017 - is taken by some other application.

Try to start it manually using the same account and see what it complains about:
```
cd C:\Program Files\Logshark\MongoDB\bin\
mongod.exe --auth --port 27017 --dbpath ..\data
```
